### ISSUE TITLE
Pokken Tournament NUD files aren't being exported correctly.

### ISSUE THREAD

**Issue by AyanamiRei1** [jam1garner/Smash-Forge#310]
Hello I've been trying to figure out texture stuff in Pokken Tournament it uses a very similar format to the one Smash 4 uses. I checked to see if Smash-Forge could open the exported NUD file and well it does but the model doesn't load and none of the information from the original version is there at all.

![aodxpur](https://user-images.githubusercontent.com/25233407/45769482-ae66dc80-bc37-11e8-9167-4bfbcddaa86b.png)
![ho9rcft](https://user-images.githubusercontent.com/25233407/45769483-ae66dc80-bc37-11e8-9b56-eb8e3f7c4fd6.png)

To be honest all I want to do is edit the material so some textures aren't shared any more.

**Comment by ScanMountGoat** [comment]
Example File:
[p654_101[1].zip](https://github.com/jam1garner/Smash-Forge/files/2403822/p654_101.1.zip)

**Comment by Demonslayerx8** [comment]
the difference between Smash and Pokken is pretty much endians, Pokken uses Little while Smash uses big, and then there's probably some small differences with offset locations I think, so saving a Pokken nud will just convert it to a smash nud, but ruins the data inside it.

**Comment by ScanMountGoat** [comment]
Files are completely rebuilt when saving. It's possible to add support for rebuilding Pokken Nuds, but only Smash 4 Nuds are supported at this time.

**Comment by AyanamiRei1** [comment]
Oh alrighty that's good to know then mainly since this Smash Forge is the only thing I can find that is able to export the materials from Pokken NUDs

**Comment by Dr-HyperCake** [comment]
I've made a bit of progress on extending support for Pokkén NUDs in response to this. The two types of NUD don't really differ apart from endianness, like DSX8 said, which makes things easier. Some of the data types in Pokkén NUDs are not used in Smash NUDs, but they're already supported by Smash Forge anyway.

There are a few things regarding the structure of material data that need to be updated based on what can be seen in Pokkén NUDs. For one thing, they contain materials which have 0 material attributes, which I'm not aware of in Smash NUDs. I'd like to try to implement proper handling of this as well as other parts of the material structure, so that it can work properly for Pokkén NUDs.

**Comment by AyanamiRei1** [comment]
Good to know some progress has been made can't wait to finally be able to edit the stupid texture ids inside the NUD.

**Comment by ScanMountGoat** [comment]
This should be fixed now. Let me know, so I can close this issue. @AyanamiRei1

**Comment by AyanamiRei1** [comment]
It's fine I'll close it myself.
