### ISSUE TITLE
If .dae has multiple vertices with more than 4 weights, the Error occurs multiple times.

### ISSUE THREAD

**Issue by InTheBeef** [jam1garner/Smash-Forge#50]
As stated, if the imported .dae has multiple vertices with 5+ weights, the error occurs multiple times, which can result in having to click through a large quantity of errors. 
![unf2aazh0](https://cloud.githubusercontent.com/assets/25026032/22629593/a53bb05a-ebe0-11e6-941d-da32a0b7166f.png)
It might be worth having the error display a box containing a list of which vertices (Vertex ID) on which objects are affected, to offer another method of finding the broken vertices later on.

**Comment by Ploaj** [comment]
I made it so it should only show the error once. Because of how collada can structure its weight controllers, it can be a little messy to give specific vertex ids. 3ds max should have the ability to auto limit the weights to 4 in it's skinning->advanced options section. I think it's called "weight limit" or something like that.
